import React from 'react';
import './Footer.css';

const Footer: React.FC = () => {
  return (
    <div className="footer">
      <p>
        <strong>How this works:</strong> Read Between extracts and analyzes
        the visible article text using local heuristics.
      </p>
      <p>
        This analysis is generated by pattern-matching algorithms and AI
        language models. Results are informational and may not capture all
        nuances.
      </p>
    </div>
  );
};

export default Footer;
