import React from 'react';

const Footer: React.FC = () => {
  return (
    <div
      style={{
        padding: '16px 0',
        borderTop: '1px solid #eee',
        marginTop: '8px',
        fontSize: '11px',
        color: '#aaa',
        textAlign: 'center',
      }}
    >
      <p style={{ margin: '0 0 4px' }}>
        <strong>How this works:</strong> Read Between extracts and analyzes
        the visible article text using local heuristics.
      </p>
      <p style={{ margin: 0 }}>
        This analysis is generated by pattern-matching algorithms, not AI
        language models. Results are informational and may not capture all
        nuances.
      </p>
    </div>
  );
};

export default Footer;
